export default interface Submission {
  _id: string,
  id: number,
  templateId: string,
  templatePackageId: string,
  name: string,
  orgId: number,
  programId: string,
  submittedDate: string,
  workbookData: {[key: string]: any},
  workflowProcessId: string,
  workflowId: string,
  statusId: string,
  year: string,
  submissionPeriodId: string,
  createdAt: string,
  updatedAt: string,
  updatedBy: string,
  isPublished: boolean,
  version: number,
  isLatest: boolean,
  parentId: string,
}