export interface Submission{
  createdAt: string,
  isLatest: boolean,
  isPublished: boolean,
  name: string,
  orgId: number,
  parentId?: string,
  period: string,
  permission: any[],
  phase: string,
  programId: string,
  programName: string,
  statusId: string,
  submissionPeriodId: string,
  submittedDate: string,
  tableData: any,
  templateId: string,
  templateName: string, 
  templatePackageId: string,
  templatePackageName: string,
  updatedAt: string,
  version: number
  workbookData: any[],
  workflowId: string,
  workflowProcessId: string,
  __v?: number,
  _id: string,
}