import SysRole from "./sysrole";

export default interface User {
  _id: string,
  hashedUsername?: string,
  title: string,
  ext?: string,
  firstName: string,
  lastName: string,
  phoneNumber: string,
  isActive: boolean,
  username: string,
  email: string,
  startDate?: string,
  endDate?: string,
  sysRole: SysRole[],
  __v?: number,
  approvedDate: string,
  creationDate: string,
  isEmailVerified: boolean,
  timestamp: string,
  updatedBy?: string,
  AppConfig?: string[],
  password: string,
  IsActive?: boolean,
  facebook?: Object,
  google?: Object,
  updatedAt?: string,
  toBeApproved?: any[] | null,
}