services:
  frontend:
      env_file:
          "./gdct-app/frontend/.env"
      build:
        context: ./gdct-app/frontend
        dockerfile: ./Dockerfile
      image: "gdctdockercontainer.azurecr.io/gdct-frontend:latest"
      ports:
        - "80:80"
      links:
        - "backend"
  backend:
    env_file:
        "./gdct-app/backend/.env"
    build:
      context: ./gdct-app/backend
      dockerfile: ./Dockerfile
    image: "gdctdockercontainer.azurecr.io/gdct-backend:latest"
    ports:
      - "8080:8080"